In [1]:
import torch

In [4]:
t = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype=torch.float32)

In [5]:
t.shape

torch.Size([3, 4])

In [8]:
rank = len(t.shape)
print(f"rank of t :{rank}")

rank of t :2


In [9]:
t.numel()

12

numel means number of elements in the tensor

In [10]:
t.reshape(4,3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [11]:
t.reshape(1,12)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [12]:
t.reshape(2,2,3)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [13]:
print(t.reshape(1,12).shape)

torch.Size([1, 12])


In [14]:
print(t.reshape(1,12).squeeze().shape)

torch.Size([12])


In [16]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

torch.Size([1, 12])


Squeeze is necessary to flatten layer before passing to neural network

In [17]:
def flatten(t):
  t=t.reshape(1,-1)
  t=t.squeeze()
  return t

In [18]:
flatten(t)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

The -1 argument passed to reshape ensures that there are enough room for all elements after reshaping