In [1]:
import torch
import numpy as np

In [3]:
t = torch.Tensor()
print(t)

tensor([])


In [4]:
print(t.shape)
print(t.dtype)
print(t.device)
print(t.layout)

torch.Size([0])
torch.float32
cpu
torch.strided


In [5]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

Type cuda means it is on gpu

cuda 0 means first gpu 

Operations between two tensors can be performed if they have same datatype and are in same device

In [6]:
data = np.array([1,2,3,4])
print(data)

[1 2 3 4]


In [7]:
torch.tensor(data)

tensor([1, 2, 3, 4])

In [8]:
torch.Tensor(data)

tensor([1., 2., 3., 4.])

In [9]:
torch.as_tensor(data)

tensor([1, 2, 3, 4])

In [10]:
torch.from_numpy(data)

tensor([1, 2, 3, 4])

The torch.Tensor gives us a constructor of class torch while rest of them gives us a factory function of class torch . Factory function is also a instance of class like objects in oop

In [11]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [12]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [13]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [14]:
torch.rand(2,2)

tensor([[0.8373, 0.6986],
        [0.5628, 0.5832]])

In [15]:
data = np.array([1,2,3])
t1=torch.Tensor(data)
t2=torch.tensor(data)
t3=torch.as_tensor(data)
t4=torch.from_numpy(data)

In [16]:
data[0]=5
data[1]=6
data[2]=7

In [17]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([5, 6, 7])
tensor([5, 6, 7])


as_tensor and from_numpy methods share the memory while tensor and Tensor method make a new copy