In [1]:
import torch

In [5]:
x= torch.empty(3)
y=torch.empty(2,3)
z=torch.empty(2,2,3)

In [6]:
print(x)
print(y)
print(z)

tensor([1.4009e-34, 0.0000e+00, 3.3631e-44])
tensor([[1.4009e-34, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[[1.4009e-34, 0.0000e+00, 0.0000e+00],
         [6.9439e-06, 1.4013e-45, 0.0000e+00]],

        [[1.3556e-19, 8.6462e+11, 3.2778e+09],
         [1.4988e+10, 3.2522e+03, 1.3023e+01]]])


In [8]:
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [9]:
print(a.dtype)

torch.float32


In [10]:
x=torch.tensor([1,45,2.5])
print(x)

tensor([ 1.0000, 45.0000,  2.5000])


In [17]:
x=torch.rand(2,2)
y=torch.rand(2,2)
z=x+y
print(f"x:{x}")
print(f"y:{y}")
print(f"z:{z}")

x:tensor([[0.1611, 0.2842],
        [0.6760, 0.3507]])
y:tensor([[0.8973, 0.7845],
        [0.7079, 0.3908]])
z:tensor([[1.0584, 1.0687],
        [1.3839, 0.7415]])


In [19]:
y.add_(x)
print(f"New y:{y}")

New y:tensor([[1.2194, 1.3529],
        [2.0599, 1.0922]])


Every operation with _ at last means inplace in pytorch

In [23]:
x=torch.rand(5,5)
y=x[:,:2]
z=x[1,3]
print(f"x:{x}")
print(f"y:{y}")
print(f"z:{z}")
print(f"Actual value : {x[1,3]}")

x:tensor([[0.8054, 0.6665, 0.4207, 0.0626, 0.4121],
        [0.5063, 0.5548, 0.4040, 0.0063, 0.5622],
        [0.5230, 0.5773, 0.5498, 0.2516, 0.1702],
        [0.1450, 0.0741, 0.8102, 0.1625, 0.9469],
        [0.5757, 0.5565, 0.9443, 0.0965, 0.8013]])
y:tensor([[0.8054, 0.6665],
        [0.5063, 0.5548],
        [0.5230, 0.5773],
        [0.1450, 0.0741],
        [0.5757, 0.5565]])
z:0.006268143653869629
Actual value : 0.006268143653869629


In [24]:
import numpy as np

In [26]:
x=torch.ones(3,4)
y=x.numpy()
print(f"x:{x}")
print(type(x))
print(f"y:{y}")
print(type(y))

x:tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
<class 'torch.Tensor'>
y:[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [27]:
x.add_(1)
print(f"x:{x}")
print(f"y:{y}")

x:tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
y:[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


Changing x also resulted in change in y since y is a numpy array of x . It is because they share the same memory location