In [1]:
import torch
import numpy as np

In [ ]:
t = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype=torch.float32)

In [ ]:
t.shape

torch.Size([3, 4])

In [ ]:
rank = len(t.shape)
print(f"rank of t :{rank}")

rank of t :2


In [ ]:
t.numel()

12

numel means number of elements in the tensor

In [ ]:
t.reshape(4,3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [ ]:
t.reshape(1,12)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [ ]:
t.reshape(2,2,3)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [ ]:
print(t.reshape(1,12).shape)

torch.Size([1, 12])


In [ ]:
print(t.reshape(1,12).squeeze().shape)

torch.Size([12])


In [ ]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

torch.Size([1, 12])


Squeeze is necessary to flatten layer before passing to neural network

In [ ]:
def flatten(t):
  t=t.reshape(1,-1)
  t=t.squeeze()
  return t

In [ ]:
flatten(t)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

The -1 argument passed to reshape ensures that there are enough room for all elements after reshaping

In [ ]:
t1=torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])
t2=torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])
t3=torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

Let us consider t1,t2,t3 are 3 images each of shape 4*4

Now we need to create a batch of these three images to pass to the network . A batch is also a tensor so we need to combine our tensors to create that  batch tensor 

In [ ]:
t =torch.stack((t1,t2,t3))
print(t)
print(t.shape)

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])
torch.Size([3, 4, 4])


In torch.size([3,4,4]), 3 indicates that there are 3 images in the batch and 4,4 indicates that each image is of size 4*4

The rank of this tensor is 3 since we need 3 different values to access a particular element

In [ ]:
t = t.reshape(3,1,4,4)
print(t)

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])


The additional 1 is to indicate that the color channel of image is greyscale . The total number of elements in the tensor doesnt get affected by that 1 since 3 * 4 * 4 * 1 is still 12 .

So finally the shape of tensor for CNN flatten operation is (batch_size,color_channel,height,width)

In [ ]:
print(f"First Image : {t[0]}")

First Image : tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])


In [ ]:
print(f"First color channel in first Image : {t[0][0]}")

First color channel in first Image : tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])


In [ ]:
print(f"First row of pixel in first color channel of first image : {t[0][0][0]}")

First row of pixel in first color channel of first image : tensor([1, 1, 1, 1])


In [ ]:
print(f"First pixel value in first row of pixel in first color channel of first image : {t[0][0][0][0]}")

First pixel value in first row of pixel in first color channel of first image : 1


Now we have to flatten the tensor

In [ ]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

If we flatten directly like this ,we are going to mix all images together like how we mixed t1,t2 and t3 since they are in the same batch .We do not want these to happen .

What we need to do is flatten only the color channel , height and width .

In [ ]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
t.flatten(start_dim=1).shape

torch.Size([3, 16])

In [2]:
t1 = torch.tensor([
    [1,2],
    [3,4],
],dtype=torch.float32)

t2 = torch.tensor([
    [5,6]
],dtype=torch.float32)

In [3]:
t1+t2

tensor([[ 6.,  8.],
        [ 8., 10.]])

Eeven though they have different shape , the operation is possible due to broadcasting

In [4]:
np.broadcast_to(t2.numpy(),t1.shape)

array([[5., 6.],
       [5., 6.]], dtype=float32)